{
    'name': 'CRM Facebook Lead Integration',
    'version': '13.0.1',
    'category': 'Social',
    'author': 'Pragmatic TechSoft Pvt Ltd.',
    'website': 'www.pragtech.co.in',
    'summary': 'Sync Facebook Leads with Odoo CRM',
    'description': 'CRM Facebook Lead Integration',
    'depends': ['crm', 'utm','odoo_lead_forms_ad_integration_hub_crm'],
    'data': [
        'security/ir.model.access.csv',
        # 'security/fb_social_dashboard_security.xml',
        'data/facebook_social_dashboard_data.xml',
        'views/social_assets_view.xml',
        'views/facebook_res_config_settings_views.xml',
        'views/crm_view.xml',
        'views/facebook_menu_view.xml',
        'views/fb_social_account_view.xml',
        'views/facebook_scedulars_view.xml',
        'views/fb_social_account_view.xml',
        'views/fb_social_media_view.xml',
    ],
    # 'images': ['images/Animated-Construction-ppc.gif'],
    'live_test_url': 'https://www.pragtech.co.in/company/proposal-form.html?id=103&name=crm-facebook-leads',
    'license': 'OPL-1',
    'price': 79.0,
    'currency': 'USD',
    'installable': True,
    'auto_install': False,
}